# Lit Responsibly automation blueprint for Inovelli VZW31-SN Red Series Switch
# This blueprint is designed for use with the ZWave JS integration.
---
blueprint:
  name: Inovelli VZW31-SN Red Series Switch
  description: Create automations for the Inovelli VZW31-SN Red Series Switch.
  domain: automation
  input:
    inovelli_vzw31sn:
      name: Inovelli VZW31-SN
      description: Available Inovelli VZW31-SN devices.
      selector:
        device:
          integration: zwave_js
          manufacturer: Inovelli
          model: VZW31-SN
          multiple: true
    command_class:
      name: Trigger Command Class
      description: Command class to trigger the automation.
      default: '91'
      selector:
        select:
          options:
            - value: '91'
              label: Central Scene
            - value: '32'
              label: Basic
            - value: '37'
              label: Switch Binary
    automation_mode:
      name: Automation mode
      description: See https://www.home-assistant.io/docs/automation/modes/
      default: single
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
    single_press:
      name: Single Press
      icon: mdi:gesture-tap
      description: Actions for single button presses.
      collapsed: true
      input:
        button_1:
          name: Button A (On/Up) Press
          description: Action to run when Button A is pressed one time.
          default: []
          selector:
            action: {}
        button_2:
          name: Button B (Off/Down) Press
          description: Action to run when Button B is pressed one time.
          default: []
          selector:
            action: {}
        button_3:
          name: Button C (Config) Press
          description: Action to run when Button C is pressed one time.
          default: []
          selector:
            action: {}
        button_4:
          name: Aux Button A (On/Up) Press
          description: Action to run when Aux Button A is pressed one time.
          default: []
          selector:
            action: {}
        button_5:
          name: Aux Button B (Off/Down) Press
          description: Action to run when Aux Button B is pressed one time.
          default: []
          selector:
            action: {}
        button_6:
          name: Aux Button C (Config) Press
          description: Action to run when Aux Button C is pressed one time.
          default: []
          selector:
            action: {}
    hold_release:
      name: Hold and Release
      icon: mdi:gesture-tap-hold
      description: Actions when a button is held and released.
      collapsed: true
      input:
        button_1_hold:
          name: Button A (On/Up) Hold
          description: Action to run when Button A is pressed and held.
          default: []
          selector:
            action: {}
        button_1_release:
          name: Button A (On/Up) Hold Release
          description: Action to run when Button A is released from hold.
          default: []
          selector:
            action: {}
        button_2_hold:
          name: Button B (Off/Down) Hold
          description: Action to run when Button B is pressed and held.
          default: []
          selector:
            action: {}
        button_2_release:
          name: Button B (Off/Down) Hold Release
          description: Action to run when Button B is released from hold.
          default: []
          selector:
            action: {}
        button_3_hold:
          name: Button C (Config) Hold
          description: Action to run when Button C is pressed and held.
          default: []
          selector:
            action: {}
        button_3_release:
          name: Button C (Config) Hold Release
          description: Action to run when Button C is released from hold.
          default: []
          selector:
            action: {}
        button_4_hold:
          name: Aux Button A (On/Up) Hold
          description: Action to run when Aux Button A is pressed and held.
          default: []
          selector:
            action: {}
        button_4_release:
          name: Aux Button A (On/Up) Hold Release
          description: Action to run when Aux Button A is released from hold.
          default: []
          selector:
            action: {}
        button_5_hold:
          name: Aux Button B (Off/Down) Hold
          description: Action to run when Aux Button B is pressed and held.
          default: []
          selector:
            action: {}
        button_5_release:
          name: Aux Button B (Off/Down) Hold Release
          description: Action to run when Aux Button B is released from hold.
          default: []
          selector:
            action: {}
        button_6_hold:
          name: Aux Button C (Config) Hold
          description: Action to run when Aux Button C is pressed and held.
          default: []
          selector:
            action: {}
        button_6_release:
          name: Aux Button C (Config) Hold Release
          description: Action to run when Aux Button C is released from hold.
          default: []
          selector:
            action: {}
    double_press:
      name: Double Press
      icon: mdi:gesture-double-tap
      description: Actions when a button is pressed 2 times.
      collapsed: true
      input:
        button_1_2x:
          name: Button A (On/Up) Double Press
          description: Action to run when Button A is pressed 2 times.
          default: []
          selector:
            action: {}
        button_2_2x:
          name: Button B (Off/Down) Double Press
          description: Action to run when Button B is pressed 2 times.
          default: []
          selector:
            action: {}
        button_3_2x:
          name: Button C (Config) Double Press
          description: Action to run when Button C is pressed 2 times.
          default: []
          selector:
            action: {}
        button_4_2x:
          name: Aux Button A (On/Up) Double Press
          description: Action to run when Aux Button A is pressed 2 times.
          default: []
          selector:
            action: {}
        button_5_2x:
          name: Aux Button B (Off/Down) Double Press
          description: Action to run when Aux Button B is pressed 2 times.
          default: []
          selector:
            action: {}
        button_6_2x:
          name: Aux Button C (Config) Double Press
          description: Action to run when Aux Button C is pressed 2 times.
          default: []
          selector:
            action: {}
    triple_press:
      name: Triple Press
      icon: mdi:gesture-double-tap
      description: Actions when a button is pressed 3 times.
      collapsed: true
      input:
        button_1_3x:
          name: Button A (On/Up) Triple Press
          description: Action to run when Button A is pressed 3 times.
          default: []
          selector:
            action: {}
        button_2_3x:
          name: Button B (Off/Down) Triple Press
          description: Action to run when Button B is pressed 3 times.
          default: []
          selector:
            action: {}
        button_3_3x:
          name: Button C (Config) Triple Press
          description: Action to run when Button C is pressed 3 times.
          default: []
          selector:
            action: {}
        button_4_3x:
          name: Aux Button A (On/Up) Triple Press
          description: Action to run when Aux Button A is pressed 3 times.
          default: []
          selector:
            action: {}
        button_5_3x:
          name: Aux Button B (Off/Down) Triple Press
          description: Action to run when Aux Button B is pressed 3 times.
          default: []
          selector:
            action: {}
        button_6_3x:
          name: Aux Button C (Config) Triple Press
          description: Action to run when Aux Button C is pressed 3 times.
          default: []
          selector:
            action: {}
    quadruple_press:
      name: Quadruple Press
      icon: mdi:gesture-double-tap
      description: Actions when a button is pressed 4 times.
      collapsed: true
      input:
        button_1_4x:
          name: Button A (On/Up) Quadruple Press
          description: Action to run when Button A is pressed 4 times.
          default: []
          selector:
            action: {}
        button_2_4x:
          name: Button B (Off/Down) Quadruple Press
          description: Action to run when Button B is pressed 4 times.
          default: []
          selector:
            action: {}
        button_3_4x:
          name: Button C (Config) Quadruple Press
          description: Action to run when Button C is pressed 4 times.
          default: []
          selector:
            action: {}
        button_4_4x:
          name: Aux Button A (On/Up) Quadruple Press
          description: Action to run when Aux Button A is pressed 4 times.
          default: []
          selector:
            action: {}
        button_5_4x:
          name: Aux Button B (Off/Down) Quadruple Press
          description: Action to run when Aux Button B is pressed 4 times.
          default: []
          selector:
            action: {}
        button_6_4x:
          name: Aux Button C (Config) Quadruple Press
          description: Action to run when Aux Button C is pressed 4 times.
          default: []
          selector:
            action: {}
    quintuple_press:
      name: Quintuple Press
      icon: mdi:gesture-double-tap
      description: Actions when a button is pressed 5 times.
      collapsed: true
      input:
        button_1_5x:
          name: Button A (On/Up) Quintuple Press
          description: Action to run when Button A is pressed 5 times.
          default: []
          selector:
            action: {}
        button_2_5x:
          name: Button B (Off/Down) Quintuple Press
          description: Action to run when Button B is pressed 5 times.
          default: []
          selector:
            action: {}
        button_3_5x:
          name: Button C (Config) Quintuple Press
          description: Action to run when Button C is pressed 5 times.
          default: []
          selector:
            action: {}
        button_4_5x:
          name: Aux Button A (On/Up) Quintuple Press
          description: Action to run when Aux Button A is pressed 5 times.
          default: []
          selector:
            action: {}
        button_5_5x:
          name: Aux Button B (Off/Down) Quintuple Press
          description: Action to run when Aux Button B is pressed 5 times.
          default: []
          selector:
            action: {}
        button_6_5x:
          name: Aux Button C (Config) Quintuple Press
          description: Action to run when Aux Button C is pressed 5 times.
          default: []
          selector:
            action: {}
  source_url: https://github.com/LitResponsibly/hassio-blueprints/blob/master/automation/inovelli/inovelli-vzw31sn-red-series-switch-scenes.yaml
mode: !input automation_mode
max_exceeded: silent
variables:
  device_ids: !input inovelli_vzw31sn
  command_class: !input command_class
trigger:
  - platform: event
    event_type: zwave_js_value_notification
condition: '{{ trigger.event.data.command_class|int(0) == command_class|int(0) and trigger.event.data.device_id in device_ids }}'
action:
- variables:
    command_class_name: '{{ trigger.event.data.command_class_name }}'
    property_key: '{{ trigger.event.data.property_key }}'
    label: '{{ trigger.event.data.label }}'
    value: '{{ trigger.event.data.value }}'
- service: logbook.log
  data:
    name: Z-Wave JS
    message: 'received event: {{ command_class_name }} - {{ label }} - {{ value }}'
- choose:
  - conditions: '{{ property_key == ''001'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_1
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_1_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_1_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_1_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_1_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_1_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_1_release
  - conditions: '{{ property_key == ''002'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_2
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_2_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_2_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_2_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_2_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_2_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_2_release
  - conditions: '{{ property_key == ''003'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_3
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_3_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_3_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_3_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_3_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_3_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_3_release
  - conditions: '{{ property_key == ''004'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_4
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_4_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_4_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_4_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_4_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_4_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_4_release
  - conditions: '{{ property_key == ''005'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_5
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_5_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_5_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_5_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_5_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_5_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_5_release
  - conditions: '{{ property_key == ''006'' }}'
    sequence:
    - choose:
      - conditions: '{{ value == ''KeyPressed'' }}'
        sequence: !input button_6
      - conditions: '{{ value == ''KeyPressed2x'' }}'
        sequence: !input button_6_2x
      - conditions: '{{ value == ''KeyPressed3x'' }}'
        sequence: !input button_6_3x
      - conditions: '{{ value == ''KeyPressed4x'' }}'
        sequence: !input button_6_4x
      - conditions: '{{ value == ''KeyPressed5x'' }}'
        sequence: !input button_6_5x
      - conditions: '{{ value == ''KeyHeldDown'' }}'
        sequence: !input button_6_hold
      - conditions: '{{ value == ''KeyReleased'' }}'
        sequence: !input button_6_release

