# onAlso automation blueprint for Inovelli VZW31-SN Red Series Switch
# This blueprint is designed for use with the ZWave JS integration.
---
blueprint:
  name: Inovelli VZW31-SN Red Series Switch
  description: Create automations for the Inovelli VZW31-SN Red Series Switch.
  domain: automation
  input:
    inovelli_vzw31_sn:
      name: Inovelli Switch
      description: Available Inovelli VZW31-SN switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Inovelli
          model: VZW31-SN
          multiple: true
  source_url: https://github.com/onalso/hassio-blueprints/blob/master/automation/inovelli/inovelli-vzw31-sn-red-series-switch-scenes.yaml
mode: single
max_exceeded: silent
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      command_class_name: Central Scene
      device_id: !input 'inovelli_vzw31_sn'
action:
  - variables:
      scene_label: '{{ trigger.event.data.label }}'
      scene_value: '{{ trigger.event.data.value }}'

